# Generated by Django 4.2.6 on 2023-10-25 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLEANcalibrationNewDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('CLEAN01', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN02', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN03', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN04', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN05', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN06', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN07', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('CLEAN08', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/CLEAN')),
                ('REF01', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF02', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF03', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF04', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF05', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF06', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF07', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('REF08', models.FileField(blank=True, null=True, upload_to='calibration/data/Inputs/Reference')),
                ('lon', models.FloatField(default=-49.0)),
                ('lat', models.FloatField(default=-27.0)),
                ('deviceId', models.IntegerField(default=0)),
            ],
        ),
    ]
