# Generated by Django 4.2.6 on 2023-10-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEANcalibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN01',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
    ]
