# Generated by Django 4.2.6 on 2023-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEANcalibration', '0003_alter_cleancalibrationnewdevicemodel_clean01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN01',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
