# Generated by Django 4.2.6 on 2023-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEANcalibration', '0004_alter_cleancalibrationnewdevicemodel_clean01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN01',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN02',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN03',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN04',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN05',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN06',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN07',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='CLEAN08',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF01',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF02',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF03',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF04',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF05',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF06',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF07',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
        migrations.AlterField(
            model_name='cleancalibrationnewdevicemodel',
            name='REF08',
            field=models.FileField(blank=True, null=True, upload_to='calibration'),
        ),
    ]
